### ISSUE TITLE
Thaumic Crafting Machine

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Thaumaturgic-Machinations#10]
I'd like a machine that is for "aspect crafting" -- it takes some items and some aspects, and spits out a magical item. it would be used for a large majority of the thaum items in the mod.  as such, it should have some spots on the graphic to connect to pipes, in addition to maybe having a seperate file for each rotation of the pipe cover.

entity size: 5x5

maybe having some vertical cylinders with fluid and some sort of crystal inside, with the fluid draining and refilling in addition to animated gears and such?

**Comment by Danielv123** [comment]
![WIP Crafting machine](https://i.imgur.com/bvt1sI3.png)

Making something infusion like

**Comment by KorGgenT** [comment]
oooh i like this one! you gonna have another layer with like magical lightning or energy beam or something between those altars in the middle?

**Comment by Danielv123** [comment]
I am adding the swirly particles like in the TC infusion :)

**Comment by Danielv123** [comment]
![Less WIP crafting machine](https://cdn.discordapp.com/attachments/336207313411112962/348762182621593600/render4.png) Also has spinning purple things, I will get the rendering setup and see if I can put this in game
