### ISSUE TITLE
Thaumic Furnace

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Thaumaturgic-Machinations#12]
Unlike the crucible, this machine does not have to do with aspects. The main use for it now is to make catalytic coal, the main fuel source of TM; and manasteel and vis-infused brick, which are major non-aspect building materials in the mod.

This machine should be a 2x2, like stone/steel furnaces. i want at least 2 tiers of them. play with the look of furnaces and make something you like!

**Comment by Xerus2000** [comment]
[entity.zip](https://github.com/KorGgenT/Thaumaturgic-Machinations/files/1185409/entity.zip)
I'll just propose these. The theme is similar to the assembling machines. Corrections could easily be made on request.

**Comment by Danielv123** [comment]
I am working on textures :) https://i.imgur.com/c6Y3DEi.png
