### ISSUE TITLE
crucible pipe connections

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Thaumaturgic-Machinations#13]
4 images for pipe connections to the crucible

**Comment by Danielv123** [comment]
I pushed and integrated some new textures a few days ago, I believe this one is resolved. If its not, just reopen.

**Comment by KorGgenT** [comment]
What i need is just the individual image with the pipes, not the whole spritesheet. that way, i can layer it and only show the necessary pipes in the entity.
