### ISSUE TITLE
Power Crystal Equipment

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Thaumaturgic-Machinations#16]
I need some equipment for the power armor grid.

4 different sizes:
32x64
64x96
160x96
224x160
Each of these could look slightly different.
I also need a 32x32 item icon for each, plus a 128x128 technology icon for each.

I want all these sizes to be the same color, with differing colors representing tiers:
Pink: Tier 1
Light Green: Tier 2
Magenta: Tier 3
(additional tiers are nice, but i only have plans for 3 for now.)

**Comment by Xerus2000** [comment]
I would recommend not making the icons only 32x32, as the vanilla textures are updated, it will look bad. I'd just recommend to go straight to 64x64, in one mod I even created a 140x140 icon which makes it look really clear.
