### ISSUE TITLE
[Incompatability] Crafting Combinator

### ISSUE THREAD

**Issue by TinkerWorX** [KorGgenT/Thaumaturgic-Machinations#36]
Version: 0.15.33, running from Steam
Mods
 * crafting_combinator_0.9.4
 * Thaumaturgic-Machinations_0.1.8

Game will give an error when starting up.

![Error](http://i.imgur.com/21beWsz.png)

I have no other mods enabled, and if I disable either mod, everything works fine.

[factorio.log](https://gist.github.com/TinkerWorX/a3d871027f80a923ba2fcc4a3d5c4998)

**Comment by KorGgenT** [comment]
supposedly this is already fixed for 0.1.9
will still test it though.

**Comment by KorGgenT** [comment]
fixed for 0.1.9
