### ISSUE TITLE
(0.1.8) Two Aspects needing the same Inputs/giving the same Outputs

### ISSUE THREAD

**Issue by chaos234** [KorGgenT/Thaumaturgic-Machinations#37]
Like stated in Discord there are 4 recipes not correct.

Images: 
![factorio_2017-09-06_04-41-15](https://user-images.githubusercontent.com/340106/30093994-52f40e9c-92c9-11e7-9ec3-7382cafec8b5.jpg)

![factorio_2017-09-06_04-41-23](https://user-images.githubusercontent.com/340106/30093999-58372aba-92c9-11e7-95f4-95e7924c0280.jpg)

Means Aversio and Avaritia are giving and needing the same amount of Spiritus and Vacuous.

**Comment by Danielv123** [comment]
I can't seem to find Avaritia mentioned anywhere on the internet, is it actually supposed to be Greed? Aversio is Spiritus + Perdito according to the FTB wiki, but need confirmation on that one.

**Comment by chaos234** [comment]
@Danielv123 - I can take a look into the Thaumonomicon an repost all bindings. But the best would be to use the TC Research Helper. Simply choose the 4.2.x Version and check at last FM and MB, after that hover over one Aspect and it shoes you the binding so that it can be corrected.

Note that in v5.x some changes where made to the aspects from what I know ;)

**Comment by Danielv123** [comment]
@chaos234 I can find Aversio in 5.1.3@http://ythri.github.io/tcresearch/, but can't find either of them in 4.2.x

**Comment by chaos234** [comment]
@Danielv123 - Oh, you are using the 5.x ones? Then you must look on them. I assumed that the 4.2.x ones are used because in 5.x there was a name change in TC.

**Comment by Danielv123** [comment]
I have pretty much only added graphics so I am by no means the person to ask for this kind of thing :P I checked the 5.x ones because that was the only place I found either of them,

@KorGgenT , can we get a clarification on what these aspects are and where we can find references for them?

**Comment by KorGgenT** [comment]
I will be changing Aversio to Magneto+Perditio
Apparently they really are set to the same ingredients in TM-Aspect-Tree-Master.lua

**Comment by KorGgenT** [comment]
Made Aversio Cognitio+Vacuous for 1.9
