### ISSUE TITLE
endgame combat error

### ISSUE THREAD

**Issue by KorGgenT** [KorGgenT/Thaumaturgic-Machinations#50]
191.319 Sprites loaded
191.319 Convert atlas 132x24 to: trilinear-filtering 
191.333 Custom inputs active: 0
191.336 Factorio initialised
191.340 Mods to disable:Failed to load mods: Error while loading recipe prototype "CW-pulse-laser-aspect-extraction" (recipe): Key "icon" not found in property tree at ROOT.recipe.CW-pulse-laser-aspect-extraction.icons[1]
Modifications: Thaumaturgic Machinations

this error occured in confliction with endgame combat

**Comment by KorGgenT** [comment]
somewhat related issue here, waiting for resolution to that one before i proceed:
https://github.com/ReikaKalseki/Reika_FactorioMods_Issues/issues/85

**Comment by KorGgenT** [comment]
unable to reproduce error

**Comment by Silvernova115** [comment]
Found the issue, problem recreated with Hydrogen Power Systems mod

https://mods.factorio.com/mod/CW-hydrogen-power

i was mistakened with EC causing the issue

**Comment by KorGgenT** [comment]
Found the error: there are two things named "CW-laser-pulse"; a gun and an explosion. this causes some issues with my inheritance function. It won't even be blacklisted correctly. The fault lies with the other mod, but I will attempt to hack a solution.

**Comment by KorGgenT** [comment]
Solution hacked in 0.1.19
Still would prefer an update to CW Hydrogen Power though
