### ISSUE TITLE
mod conflict with Food Industry

### ISSUE THREAD

**Issue by yuanjie000** [KorGgenT/Thaumaturgic-Machinations#51]
![qq 20180814180041](https://user-images.githubusercontent.com/20902900/44085538-78e73738-9fec-11e8-8c97-531d7246212a.png)
![image](https://user-images.githubusercontent.com/20902900/44086224-7500cdda-9fee-11e8-9667-30b5382bb0bf.png)

Thaumaturgic-Machinations_0.1.18
aai-programmable-vehicles_0.4.4
WhistleStopFactories_0.1.1

**Comment by KorGgenT** [comment]
initial thoughts: not a problem with AAI, but a problem with whistle stop factories

**Comment by KorGgenT** [comment]
no issue when loading whistle stop factories by itself with TM, nor is there a problem when loading aai with TM. Problem lies with some other mod that's not listed. can you give me a mod list? @yuanjie000

**Comment by KorGgenT** [comment]
also, can you attach a log file

**Comment by yuanjie000** [comment]
[log](https://paste.ubuntu.com/p/cm4MMC4scr/)
[modlist](https://paste.ubuntu.com/p/8Q6sjmGrCY/)

**Comment by KorGgenT** [comment]
I started a game with this modlist and found no errors. Are you still getting the error? are the mods the most up to date? if so, can you send me a copy of your save that you're getting the trouble with?

**Comment by yuanjie000** [comment]
Still have this problem. All the mod are up to date. The problem was happened when I starting factorio, i think is not related to save. (I remove all the save and it still.)

**Comment by KorGgenT** [comment]
could you start a new map without TM and then send me that save? it will be easier to sync the mods then.

**Comment by yuanjie000** [comment]
[without TM.zip](https://github.com/KorGgenT/Thaumaturgic-Machinations/files/2289214/without.TM.zip)

**Comment by KorGgenT** [comment]
mod incompatibility found: the mod in question is Food Industry. Will investigate more tomorrow.

**Comment by yuanjie000** [comment]
thanks for you patient

**Comment by KorGgenT** [comment]
Fixed the conflict with Food Industry in 1.19
Currently looking for the second error

**Comment by KorGgenT** [comment]
found some more conflicts. currently runs with the modlist @ 1.19 update.
