### ISSUE TITLE
Failed to load mod

### ISSUE THREAD

**Issue by theonlywolfboy** [KorGgenT/Thaumaturgic-Machinations#57]
![error Thaum](https://user-images.githubusercontent.com/6424142/65357810-435c3700-dbf8-11e9-8635-025a662398a4.JPG)
Hi, got the error message above when i loaded your mod into my game.
facorio version 0.17.69 
hope it's not a hassle to fix.
Greetings

**Comment by KorGgenT** [comment]
what other mods do you have in your game?

**Comment by theonlywolfboy** [comment]
Well i have a whole bunch of mods in my game. here is the log file from my most recent startup. I also  have the pressurized fluids mod but it's disabled because of another failed oad
[factorio-current.log](https://github.com/KorGgenT/Thaumaturgic-Machinations/files/3637800/factorio-current.log)
I hope you can unravel that because it's a long list. if it's to hard i can make screenshots of the in game list

**Comment by theonlywolfboy** [comment]
![List2](https://user-images.githubusercontent.com/6424142/65360040-aa7cea00-dbfe-11e9-8f8b-922194f32399.JPG)
![List3](https://user-images.githubusercontent.com/6424142/65360041-aa7cea00-dbfe-11e9-9ea1-7b0fe3dbf490.JPG)
![List4](https://user-images.githubusercontent.com/6424142/65360042-aa7cea00-dbfe-11e9-85c0-04170d009a07.JPG)
![List5](https://user-images.githubusercontent.com/6424142/65360043-aa7cea00-dbfe-11e9-8861-1dce9e5a250d.JPG)
![List1](https://user-images.githubusercontent.com/6424142/65360044-aa7cea00-dbfe-11e9-9a14-04bd52f0e019.JPG)
I already made an easier overview of all the mods I have in my game
Sorry it's such a huge list but I would like to mention that it's been a long time since I played and on 0.16 i've never had any issue with all of these mods.

**Comment by theonlywolfboy** [comment]
[Test.zip](https://github.com/KorGgenT/Thaumaturgic-Machinations/files/3699286/Test.zip)
Hi, another mod auther asked for a savefile to easely get the mods to test with, was thinking it could be usefull for you too.

And sorry if my last comment came over wrong, its not to rush you it was just to state that i'll be staying on 0.16 until you could possibly fix it, so just take your time.

**Comment by archielecroy** [comment]
Thaumaturgic Machinations 0.1.24 conflicts with Flare Stack 2.2.3
I ran into the same error, so I did a binary search approach to narrow down the conflict. 

I'm not very experienced with lua or factorio modding, but it looks like TM.inherit_helper is having issues with the "-flaring" and "-incineration" recipes from FS. Both recipes have non-nil, empty results.
