### ISSUE TITLE
File not found hr-boiling-green-patch-mask.png

### ISSUE THREAD

**Issue by archielecroy** [KorGgenT/Thaumaturgic-Machinations#58]
Error on startup:
`Filed to load mods: File not found: __base__/graphics/entity/chemical-plant/hr-boiling-green-patch-mask.png`

Factorio version:
0.17.69 (build 47194, win64, steam)

Thaumaturgic Machinations version:
0.1.24

Steps to reproduce:
1. Download latest Factorio
2. add TM either via the in-game mod broswer or manually dropping the zip in the mods folder
3. (re)start Factorio

**Comment by archielecroy** [comment]
Found the same issue reported on [Napu's Mod](https://mods.factorio.com/mod/NapusMod/discussion/5d6f4274df0937000b8c5453) . Took the image from that mod and added it to this one and the game successfully reached the main menu.

**Comment by archielecroy** [comment]
Napus Mod had a similar issue, so I took the chemical plant images from it and adapted it's chemical-plant-2.lua to entities.lua and got TM to launch. 
So it seems like TM is trying to reference non-existent images in the chemical-plant directory.

**Comment by archielecroy** [comment]
I'll try to get to it later this week. 
Since it involves using some images from the other mod, I looked into licensing for factorio mods. According to the [wiki](https://wiki.factorio.com/Modding#Licensing), unless a mod states otherwise, it defaults to a [creative commons license](https://creativecommons.org/licenses/by-nc/4.0/). So we could attribute the other mod for the images, but I'm assuming the images came from somewhere else originally, since both mods referenced them. Perhaps an earlier build of Factorio?

**Comment by KorGgenT** [comment]
they were originally from factorio's files, yes an earlier build.

**Comment by KorGgenT** [comment]
i'm gonna wait on releasing a new version on the mod portal until this issue is fixed, as it's pretty important.

**Comment by KorGgenT** [comment]
seems to no longer be an error.
