### ISSUE TITLE
How to make aversio?

### ISSUE THREAD

**Issue by Drtyranid37** [KorGgenT/Thaumaturgic-Machinations#63]
So I'm at a standstill. I can't make wands without aversio but I can't get aversio without wands. How do I get one without the other? Or do I just need to progress further into the mod

**Comment by KorGgenT** [comment]
well... i haven't looked at this mod in years. from what i remember you can just combine appropriate aspects into higher ones if you can't directly get it from an item. however, i could have sworn there's at least one item that has it.

**Comment by Danielv123** [comment]
Either from crotinnium if you have angels ores or by combining Vacuous and Cognitio
